=== Madhan-091296/Robot-Framework/Day6/XSD_with_some_validations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="TradeHUB">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="header">
          <xs:complexType>
            <xs:all>
              <xs:element name="messageType">
                <xs:simpleType>
              		<xs:restriction base="xs:string">
                      <xs:enumeration value="NEWM"/> <!-- Ensure only one of these values exist  -->
     				  <xs:enumeration value="CANC"/>
                      <xs:enumeration value="TEST"/>
                      <xs:enumeration value="ECHO"/>
    				</xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="dataSourceCode">        
                <xs:simpleType>
              		<xs:restriction base="xs:string">
                		<xs:minLength value="2"/> <!-- Ensure there is at least 1 character of data -->
    				</xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="msgDateTimestamp"> <!-- dateTime format so space between date and time in xml can be validated-->
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element type="xs:long" name="orderId"/>
            </xs:all>
          </xs:complexType>
        </xs:element>
        <xs:element name="TradeParent">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="BlockTrade">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="accrualDays"/>
                    <xs:element type="xs:string" name="accrualType"/>
                    <xs:element type="xs:string" name="accrualTypeName"/>
                    <xs:element type="xs:byte" name="allocationCount"/>
                    <xs:element type="xs:string" name="allocdDatetime"/>
                    <xs:element type="xs:string" name="assetCurrency"/>
                    <xs:element type="xs:string" name="baseTicker"/>
                    <xs:element type="xs:float" name="blockCommissionAmt"/>
                    <xs:element type="xs:float" name="blockCommissionExecutionAmt"/>
                    <xs:element type="xs:float" name="blockCommissionResearchAmt"/>
                    <xs:element type="xs:float" name="blockIncAmt"/>
                    <xs:element type="xs:float" name="blockOthrFee"/>
                    <xs:element type="xs:float" name="blockProceedsAmount"/>
                    <xs:element type="xs:short" name="blockQty"/>
                    <xs:element type="xs:float" name="blockRegfFee"/>
                    <xs:element type="xs:float" name="blockSellingConcession"/>
                    <xs:element type="xs:float" name="blockTotalFee"/>
                    <xs:element type="xs:float" name="blockTotalTrade"/>
                    <xs:element type="xs:string" name="bloombergMkteSect"/>
                    <xs:element type="xs:byte" name="calcPrecision"/>
                    <xs:element type="xs:float" name="contractSize"/>
                    <xs:element type="xs:string" name="contraPartyAcronym"/>
                    <xs:element type="xs:string" name="contraPartyName"/>
                    <xs:element type="xs:string" name="countryOfRisk"/>
                    <xs:element type="xs:byte" name="couponRate"/>
                    <xs:element type="xs:string" name="crdAssetClassCd"/>
                    <xs:element type="xs:int" name="crdSecurityId"/>
                    <xs:element type="xs:string" name="createDatetime"/>
                    <xs:element type="xs:string" name="createUser"/>
                    <xs:element type="xs:string" name="createUsername"/>
                    <xs:element type="xs:string" name="crossOrderID"/>
                    <xs:element type="xs:string" name="currencyTransactionCode"/>
                    <xs:element type="xs:byte" name="currentFactor"/>
                    <xs:element type="xs:string" name="cusip"/>
                    <xs:element type="xs:string" name="dataSourceCode"/>
                    <xs:element type="xs:string" name="datedDt"/>
                    <xs:element type="xs:string" name="dayBasis"/>
                    <xs:element type="xs:short" name="eagleSecAlias"/>
                    <xs:element type="xs:string" name="exchCountry"/>
                    <xs:element type="xs:date" name="executedTradeDate"/>
                    <xs:element type="xs:time" name="executedTradeEndTime"/>
                    <xs:element type="xs:time" name="executedTradeStartTime"/>
                    <xs:element type="xs:string" name="execYield"/>
                    <xs:element type="xs:string" name="expireDate"/>
                    <xs:element type="xs:string" name="exportDateTimestamp"/>
                    <xs:element type="xs:string" name="ipoSoFlag" minOccurs="0"/> <!-- for tag to be optional -->
                    <xs:element type="xs:string" name="isin"/>
                    <xs:element type="xs:string" name="isitcAssetTypeBBHDM"/>
                    <xs:element type="xs:string" name="isitcSecurityTypeBBHDM"/>
                    <xs:element type="xs:string" name="issueCountry"/>
                    <xs:element type="xs:float" name="issuerIssuer"/>
                    <xs:element type="xs:string" name="issuerName"/> <!-- Issuer Name has to be string -->
                    <xs:element type="xs:string" name="listExchange"/>
                    <xs:element type="xs:string" name="longShortIndicator"/>
                    <xs:element type="xs:float" name="lotSize"/>
                    <xs:element type="xs:string" name="managerInitials"/>
                    <xs:element type="xs:string" name="managerName"/>
                    <xs:element type="xs:string" name="matureDate"/>
                    <xs:element type="xs:string" name="messageType"/>
                    <xs:element type="xs:string" name="omsExecBroker"/>
                    <xs:element type="xs:string" name="omsExecBrokerName"/>
                    <xs:element type="xs:string" name="openClose"/>
                    <xs:element type="xs:string" name="optionExpirationType"/>
                    <xs:element type="xs:string" name="orderDuration"/>
                    <xs:element type="xs:string" name="orderExchCd"/>
                    <xs:element type="xs:long" name="orderId"/>
                    <xs:element type="xs:string" name="orderReasonCd"/>
                    <xs:element type="xs:string" name="orderReasonDesc"/>
                    <xs:element type="xs:string" name="orderSide"/>
                    <xs:element type="xs:string" name="originalOrderID"/>
                    <xs:element type="xs:float" name="parentIssuer"/>
                    <xs:element type="xs:string" name="parentIssuereName"/>
                    <xs:element type="xs:float" name="price"/>
                    <xs:element type="xs:string" name="prinAgncy"/>
                    <xs:element type="xs:string" name="privatePlacementFlag"/>
                    <xs:element type="xs:string" name="putCall"/>
                    <xs:element type="xs:byte" name="reasonCode"/>
                    <xs:element type="xs:string" name="reasonDesc"/>
                    <xs:element type="xs:string" name="restrictedFlag144A"/>
                    <xs:element type="xs:string" name="revisionFlag"/>
                    <xs:element type="xs:byte" name="secConversionFactor"/>
                    <xs:element type="xs:string" name="secName"/>
                    <xs:element type="xs:string" name="secTypeCd"/>
                    <xs:element type="xs:int" name="sedol"/>
                    <xs:element type="xs:string" name="sellCrossOrderID"/>
                    <xs:element type="xs:string" name="sentAcctDatetime"/>
                    <xs:element type="xs:date" name="settlementDate"/>
                    <xs:element type="xs:string" name="shortDescription"/>
                    <xs:element type="xs:short" name="sirsSecurityId"/>
                    <xs:element type="xs:string" name="smaCommentary"/>
                    <xs:element type="xs:string" name="statusIndicator"/>
                    <xs:element type="xs:string" name="strikePrice"/>
                    <xs:element type="xs:byte" name="syndicateCount"/>
                    <xs:element type="xs:string" name="ticker"/>
                    <xs:element type="xs:string" name="tickerExchange"/>
                    <xs:element type="xs:string" name="toTraderDatetime"/>
                    <xs:element type="xs:string" name="trade17A7Flag"/>
                    <xs:element type="xs:date" name="tradeDate"/>
                    <xs:element type="xs:date" name="tradePlacedDate"/>
                    <xs:element type="xs:time" name="tradePlacedTime"/>
                    <xs:element type="xs:string" name="traderInitials"/>
                    <xs:element type="xs:string" name="traderName"/>
                    <xs:element type="xs:string" name="tradetTransIndicator"/>
                    <xs:element type="xs:string" name="transactionType"/>
                    <xs:element type="xs:string" name="transType"/>
                    <xs:element type="xs:string" name="typeTransactionCode"/>
                    <xs:element type="xs:string" name="underlying_country_of_risk"/>
                    <xs:element type="xs:string" name="underlying_sirs_secId"/>
                    <xs:element type="xs:string" name="underlyingCrdSecId"/>
                    <xs:element type="xs:string" name="underlyingCusip"/>
                    <xs:element type="xs:string" name="underlyingEagleSecAlias"/>
                    <xs:element type="xs:string" name="underlyingIsin"/>
                    <xs:element type="xs:string" name="underlyingIssueCountry"/>
                    <xs:element type="xs:string" name="underlyingListExchange"/>
                    <xs:element type="xs:string" name="underlyingSecName"/>
                    <xs:element type="xs:string" name="underlyingSecType"/>
                    <xs:element type="xs:string" name="underlyingSedol"/>
                    <xs:element type="xs:string" name="clientSecurityId"/>
                    <xs:element type="xs:string" name="underlyingShortDescription"/>
                    <xs:element name="syndicateDetail">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="managementFeeCps"/>
                          <xs:element type="xs:string" name="pctOrder"/>
                          <xs:element type="xs:string" name="quantity"/>
                          <xs:element type="xs:string" name="sellingConcessionCps"/>
                          <xs:element type="xs:string" name="syndicateAcronym"/>
                          <xs:element type="xs:string" name="totalConcessionCps"/>
                          <xs:element type="xs:string" name="underwriterExpenseCps"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="TradeChild">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="accountingTrade">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:short" name="allocQty"/>
                                <xs:element type="xs:float" name="allocSellingConcession"/>
                                <xs:element type="xs:float" name="allocTotalFee"/>
                                <xs:element type="xs:string" name="brokerReasonCd"/>
                                <xs:element type="xs:string" name="brokerReasonDesc"/>
                                <xs:element type="xs:string" name="clearBroker"/>
                                <xs:element type="xs:string" name="clearingBrokerAcronymBBHDM"/>
                                <xs:element type="xs:string" name="comments"/>
                                <xs:element type="xs:float" name="commisionEffRate"/>
                                <xs:element type="xs:float" name="commission"/>
                                <xs:element type="xs:float" name="commissionExecutionAmt"/>
                                <xs:element type="xs:string" name="commissionInd"/>
                                <xs:element type="xs:float" name="commissionResearchAmt"/>
                                <xs:element type="xs:string" name="conditionInd"/>
                                <xs:element type="xs:string" name="creditBroker"/>
                                <xs:element type="xs:string" name="crossTradeId"/>
                                <xs:element type="xs:string" name="custodianAccountBBHDM"/>
                                <xs:element type="xs:string" name="custodianBICBBHDM"/>
                                <xs:element type="xs:string" name="custodianFundNumber"/>
                                <xs:element type="xs:string" name="custodianName"/>
                                <xs:element type="xs:string" name="custodianNameBBHDM"/>
                                <xs:element type="xs:string" name="deliveryType"/>
                                <xs:element type="xs:string" name="fundCurrency"/>
                                <xs:element type="xs:float" name="localNetAmount"/>
                                <xs:element type="xs:byte" name="localToBaseFXRate"/>
                                <xs:element type="xs:string" name="lotBasedFund"/>
                                <xs:element type="xs:string" name="omsAcctCode"/>
                                <xs:element type="xs:string" name="omsAcctEglEntityId"/>
                                <xs:element type="xs:string" name="omsAcctName"/>
                                <xs:element type="xs:string" name="omsCrossingAcct"/>
                                <xs:element type="xs:string" name="omsCrossingAcctEglEntityId"/>
                                <xs:element type="xs:string" name="omsCrossingAcctName"/>
                                <xs:element type="xs:string" name="originalTradeId"/>
                                <xs:element type="xs:float" name="otherFee"/>
                                <xs:element type="xs:string" name="pmUser"/>
                                <xs:element type="xs:string" name="pmUserName"/>
                                <xs:element type="xs:string" name="primeBroker"/>
                                <xs:element type="xs:float" name="principalAmt"/>
                                <xs:element type="xs:string" name="pset"/>
                                <xs:element type="xs:float" name="secFee"/>
                                <xs:element type="xs:string" name="securityCurrency"/>
                                <xs:element type="xs:byte" name="securityToUsdRate"/>
                                <xs:element type="xs:string" name="settlementAccountCode"/>
                                <xs:element type="xs:string" name="settlementAccountName"/>
                                <xs:element type="xs:string" name="settlementAcctEglEntityId"/>
                                <xs:element type="xs:string" name="settlementCrossingAcct"/>
                                <xs:element type="xs:string" name="settlementCrossingAcctCustodianName"/>
                                <xs:element type="xs:string" name="settlementCrossingAcctEglEntityId"/>
                                <xs:element type="xs:string" name="settlementCrossingAcctFundNumber"/>
                                <xs:element type="xs:string" name="settlementCrossingAcctName"/>
                                <xs:element type="xs:string" name="stepOutBroker"/>
                                <xs:element type="xs:byte" name="totalLotsRelieved"/>
                                <xs:element type="xs:string" name="tradedCurrency"/>
                                <xs:element type="xs:string" name="tradedCurrencyToUsd"/>
                                <xs:element type="xs:float" name="tradedInterest"/>
                                <xs:element type="xs:string" name="tradedInterestCcy"/>
                                <xs:element type="xs:byte" name="tradedToUsdRate"/>
                                <xs:element type="xs:int" name="tradeId"/>
                                <xs:element name="tradeLot">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element type="xs:int" name="lotId"/>
                                      <xs:element type="xs:string" name="relievingLotBrokerReason"/>
                                      <xs:element type="xs:string" name="relievingLotFollowsFundMethod"/>
                                      <xs:element type="xs:string" name="relievingLotOmsExecBroker"/>
                                      <xs:element type="xs:string" name="relievingLotOrderId"/>
                                      <xs:element type="xs:string" name="relievingLotPrice"/>
                                      <xs:element type="xs:string" name="relievingLotQty"/>
                                      <xs:element type="xs:string" name="relievingLotReliefMethodCd"/>
                                      <xs:element type="xs:string" name="relievingLotReliefMethodDesc"/>
                                      <xs:element type="xs:string" name="relievingLotSettleDate"/>
                                      <xs:element type="xs:string" name="relievingLotSettleExecBroker"/>
                                      <xs:element type="xs:string" name="relievingLotTradeDate"/>
                                      <xs:element type="xs:string" name="relievingLotTradeId"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element type="xs:string" name="entityFlag"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="FH_CountryOfQuotation"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Madhan-091296/Robot-Framework/Day6/XMLToBeValidated.xml
<?xml version="1.0" encoding="UTF-8"?>
<TradeHUB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSD_with_some_validations.xsd">
	<header>
		<dataSourceCode>CHRIVER</dataSourceCode>
		<messageType>NEWMaa</messageType>
		<msgDateTimestamp>2024-12-04 BS11:19:08</msgDateTimestamp>
		<orderId>3891640168</orderId>
	</header>
	<TradeParent>
		<BlockTrade>
			<accrualDays/>
			<accrualType/>
			<accrualTypeName/>			
			<allocdDatetime>2024-12-04 10:29:08</allocdDatetime>
			<allocationCount>1</allocationCount>
			<assetCurrency>USD</assetCurrency>
			<baseTicker>PSA</baseTicker>
			<blockCommissionAmt>40.00</blockCommissionAmt>
			<blockCommissionExecutionAmt>40.00</blockCommissionExecutionAmt>
			<blockCommissionResearchAmt>0.00</blockCommissionResearchAmt>
			<blockIncAmt>0.00</blockIncAmt>
			<blockOthrFee>0.00</blockOthrFee>
			<blockProceedsAmount>298293.50</blockProceedsAmount>
			<blockQty>1000</blockQty>
			<blockRegfFee>0.00</blockRegfFee>
			<blockSellingConcession>0.0000</blockSellingConcession>
			<blockTotalFee>0.00</blockTotalFee>
			<blockTotalTrade>298253.50</blockTotalTrade>
			<bloombergMkteSect>EQUITY</bloombergMkteSect>
			<calcPrecision>2</calcPrecision>
			<contractSize>1.00</contractSize>
			<contraPartyAcronym>INST</contraPartyAcronym>
			<contraPartyName>INSTINET, INC.</contraPartyName>
			<countryOfRisk>US</countryOfRisk>
			<couponRate>0</couponRate>
			<crdAssetClassCd/>
			<crdSecurityId>1202004068</crdSecurityId>
			<createDatetime>2024-12-04 10:24:47</createDatetime>
			<createUser>SHELTPJ</createUser>
			<createUsername>PHIL SHELTON</createUsername>
			<crossOrderID/>
			<currencyTransactionCode>USD</currencyTransactionCode>
			<currentFactor>1</currentFactor>
			<cusip>74460D109</cusip>
			<dataSourceCode>CHRIVER</dataSourceCode>
			<datedDt/>
			<dayBasis/>
			<eagleSecAlias>12696</eagleSecAlias>
			<exchCountry>US</exchCountry>
			<executedTradeDate>2024-01-08</executedTradeDate>
			<executedTradeEndTime>00:00:00</executedTradeEndTime>
			<executedTradeStartTime>00:00:00</executedTradeStartTime>
			<execYield/>
			<expireDate/>
			<exportDateTimestamp>2024-12-04 11:19:01</exportDateTimestamp>
			<!-- <ipoSoFlag>N</ipoSoFlag> -->
			<isin>US74460D1090</isin>
			<isitcAssetTypeBBHDM/>
			<isitcSecurityTypeBBHDM/>
			<issueCountry>US</issueCountry>
			<issuerIssuer>74460D</issuerIssuer>
			<issuerName>PUBLIC STORAGE</issuerName>
			<listExchange>XNYS</listExchange>
			<longShortIndicator>N</longShortIndicator>
			<lotSize>1.00</lotSize>
			<managerInitials>DLM</managerInitials>
			<managerName>DANA MEISSNER</managerName>
			<matureDate/>
			<messageType>NEWM</messageType>
			<omsExecBroker>NEWPORT</omsExecBroker>
			<omsExecBrokerName>INSTINET NEWPORT APPLICATION</omsExecBrokerName>
			<openClose>O</openClose>
			<optionExpirationType/>
			<orderDuration>GTC</orderDuration>
			<orderExchCd>XNYS</orderExchCd>
			<orderId>3891640168</orderId>
			<orderReasonCd>NEWS</orderReasonCd>
			<orderReasonDesc>EQ: NEWS/RESEARCH REVISIONS</orderReasonDesc>
			<orderSide>BUY</orderSide>
			<originalOrderID/>
			<parentIssuer>74460D</parentIssuer>
			<parentIssuereName>PUBLIC STORAGE</parentIssuereName>
			<price>298.2535</price>
			<prinAgncy>A</prinAgncy>
			<privatePlacementFlag>N</privatePlacementFlag>
			<putCall/>
			<reasonCode>01</reasonCode>
			<reasonDesc>COMMISSION</reasonDesc>
			<restrictedFlag144A>N</restrictedFlag144A>
			<revisionFlag>N</revisionFlag>
			<secConversionFactor>1</secConversionFactor>
			<secName>PUBLIC STORAGE - REIT</secName>
			<secTypeCd>COMREIT</secTypeCd>
			<sedol>2852533</sedol>
			<sellCrossOrderID/>
			<sentAcctDatetime>2024-12-04 10:29:19</sentAcctDatetime>
			<settlementDate>2024-01-10</settlementDate>
			<shortDescription>PUBLIC STORAGE, INC.</shortDescription>
			<sirsSecurityId>29544</sirsSecurityId>
			<smaCommentary/>
			<statusIndicator>ACCT</statusIndicator>
			<strikePrice/>
			<syndicateCount>0</syndicateCount>
			<ticker>PSA</ticker>
			<tickerExchange/>
			<toTraderDatetime>2024-12-04 10:24:47</toTraderDatetime>
			<trade17A7Flag>N</trade17A7Flag>
			<tradeDate>2024-01-08</tradeDate>
			<tradePlacedDate>2024-01-08</tradePlacedDate>
			<tradePlacedTime>00:00:00</tradePlacedTime>
			<traderInitials>CXH</traderInitials>
			<traderName>CHAD HUDSON</traderName>
			<tradetTransIndicator/>
			<transactionType>BUY</transactionType>
			<transType>BUYL</transType>
			<typeTransactionCode>B</typeTransactionCode>
			<underlying_country_of_risk/>
			<underlying_sirs_secId/>
			<underlyingCrdSecId/>
			<underlyingCusip/>
			<underlyingEagleSecAlias/>
			<underlyingIsin/>
			<underlyingIssueCountry/>
			<underlyingListExchange/>
			<underlyingSecName/>
			<underlyingSecType/>
			<underlyingSedol/>
			<clientSecurityId>E12696</clientSecurityId>
			<underlyingShortDescription/>
			<syndicateDetail>
				<managementFeeCps/>
				<pctOrder/>
				<quantity/>
				<sellingConcessionCps/>
				<syndicateAcronym/>
				<totalConcessionCps/>
				<underwriterExpenseCps/>
			</syndicateDetail>
			<TradeChild>
				<accountingTrade>
					<allocQty>1000</allocQty>
					<allocSellingConcession>0.0000</allocSellingConcession>
					<allocTotalFee>0.00</allocTotalFee>
					<brokerReasonCd>SOFT</brokerReasonCd>
					<brokerReasonDesc>SOFT DOLLAR</brokerReasonDesc>
					<clearBroker/>
					<clearingBrokerAcronymBBHDM/>
					<comments>COMMENTS: : SPECIAL_INSTRUCTIONS:</comments>
					<commisionEffRate>4.00</commisionEffRate>
					<commission>40.00</commission>
					<commissionExecutionAmt>40.00</commissionExecutionAmt>
					<commissionInd>CPS</commissionInd>
					<commissionResearchAmt>0.00</commissionResearchAmt>
					<conditionInd/>
					<creditBroker/>
					<crossTradeId/>
					<custodianAccountBBHDM/>
					<custodianBICBBHDM/>
					<custodianFundNumber>22V1</custodianFundNumber>
					<custodianName>STATE STREET BOSTON</custodianName>
					<custodianNameBBHDM/>
					<deliveryType>DTC</deliveryType>
					<fundCurrency>USD</fundCurrency>
					<localNetAmount>298293.50</localNetAmount>
					<localToBaseFXRate>1</localToBaseFXRate>
					<lotBasedFund>Y</lotBasedFund>
					<omsAcctCode>FPBF</omsAcctCode>
					<omsAcctEglEntityId>MFE00047</omsAcctEglEntityId>
					<omsAcctName>FEDERATED HERMES PRUDENT BEAR FUND</omsAcctName>
					<omsCrossingAcct/>
					<omsCrossingAcctEglEntityId/>
					<omsCrossingAcctName/>
					<originalTradeId/>
					<otherFee>0.00</otherFee>
					<pmUser/>
					<pmUserName/>
					<primeBroker/>
					<principalAmt>298253.50</principalAmt>
					<pset>DTCYUS33</pset>
					<secFee>0.00</secFee>
					<securityCurrency>USD</securityCurrency>
					<securityToUsdRate>1</securityToUsdRate>
					<settlementAccountCode>FPBF</settlementAccountCode>
					<settlementAccountName>FEDERATED HERMES PRUDENT BEAR FUND</settlementAccountName>
					<settlementAcctEglEntityId>MFE00047</settlementAcctEglEntityId>
					<settlementCrossingAcct/>
					<settlementCrossingAcctCustodianName/>
					<settlementCrossingAcctEglEntityId/>
					<settlementCrossingAcctFundNumber/>
					<settlementCrossingAcctName/>
					<stepOutBroker/>
					<totalLotsRelieved>1</totalLotsRelieved>
					<tradedCurrency>USD</tradedCurrency>
					<tradedCurrencyToUsd>USD</tradedCurrencyToUsd>
					<tradedInterest>0.00</tradedInterest>
					<tradedInterestCcy/>
					<tradedToUsdRate>1</tradedToUsdRate>
					<tradeId>1261915588</tradeId>
					<tradeLot>
						<lotId>1263032281</lotId>
						<relievingLotBrokerReason/>
						<relievingLotFollowsFundMethod/>
						<relievingLotOmsExecBroker/>
						<relievingLotOrderId/>
						<relievingLotPrice/>
						<relievingLotQty/>
						<relievingLotReliefMethodCd/>
						<relievingLotReliefMethodDesc/>
						<relievingLotSettleDate/>
						<relievingLotSettleExecBroker/>
						<relievingLotTradeDate/>
						<relievingLotTradeId/>
					</tradeLot>
					<entityFlag>FHI</entityFlag>
				</accountingTrade>
			</TradeChild>
			<FH_CountryOfQuotation>US</FH_CountryOfQuotation>
		</BlockTrade>
	</TradeParent>
</TradeHUB>
